apiVersion: v1
kind: Pod
metadata:
  name: redis
 labels:
    app: redis
spec:
 affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: DoesNotExist
            values:
            - sql
  containers:
  - name: redis-container
    image: nginx:perl